### ISSUE TITLE
License

### ISSUE THREAD

**Issue by adityardesai** [EducationalTestingService/stanford-thrift#31]
Hello folks

What is the type of the license for this code base?? Apache 2.0 or MIT or any other?

Thanks

**Comment by dmnapolitano** [comment]
Hi @adityardesai, sorry for the lack of LICENSE file.  The license is in the Java files I've written (e.g. https://github.com/EducationalTestingService/stanford-thrift/blob/master/src/org/ets/research/nlp/stanford_thrift/coref/StanfordCorefThrift.java) and it's GPL 2.0.  Thanks for your interest 😄
